# Generated by Django 4.0.1 on 2022-01-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toplevelcomment',
            name='contents',
            field=models.TextField(),
        ),
    ]
